# Generated by Django 4.0.3 on 2023-06-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketplace.item'),
        ),
    ]
