# Generated by Django 4.0.3 on 2023-07-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_discussion_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='receiver',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.AlterUniqueTogether(
            name='discussion',
            unique_together={('receiver_id', 'sender_id')},
        ),
    ]
