# Generated by Django 4.0.3 on 2023-07-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_rename_receiver_discussion_receiver_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='discussion',
            unique_together={('receiver', 'sender')},
        ),
    ]
