# Generated by Django 4.0.3 on 2023-06-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_category_options_item_last_update_item_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='customer',
        ),
    ]
