# Generated by Django 4.0.3 on 2023-06-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_rename_user_favorite_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='customer',
            new_name='user',
        ),
    ]
