# Generated by Django 4.0.3 on 2023-06-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_rename_customer_favorite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='customer',
        ),
    ]
