# Generated by Django 4.0.3 on 2023-06-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_rename_user_favorite_customer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('customer', 'item')},
        ),
    ]
